// Generated by https://quicktype.io

export interface SuccessResponse {
  message: string;
  data?:    Data;
}

export interface Data {
  id:       number;
  name:     string;
  surnames: string;
  email:    string;
  createAt: string;
}
